name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-static-release
            arch: x86_64
            platform: windows
          - os: ubuntu-latest
            triplet: x64-linux-release
            arch: x86_64
            platform: linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_GIT_COMMIT_ID: 'a325228200d7f229f3337e612e0077f2a5307090'

    steps:
      - name: Install gcc-13
        if: runner.os == 'Linux'
        run: |
          wget --no-verbose http://kayari.org/gcc-latest/gcc-latest_13.0.1-20230212git06ca0c9abb26.deb
          sudo dpkg -i gcc-latest_13.0.1-20230212git06ca0c9abb26.deb
          echo "/opt/gcc-latest/bin" >> $GITHUB_PATH
          echo "LD_RUN_PATH=/opt/gcc-latest/lib64" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
          
      - name: Setup vcpkg (windows)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: 'C:\vcpkg'
          vcpkgGitCommitId: '${{ env.VCPKG_GIT_COMMIT_ID }}'

      - name: Setup vcpkg (non-windows)
        if: runner.os != 'Windows'
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '${{ env.VCPKG_GIT_COMMIT_ID }}'

      - name: Build & Test project
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=Release', '-DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}', '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded']"

          buildPreset: 'ninja-vcpkg'

          testPreset: 'ninja-vcpkg'
          testPresetAdditionalArgs: "['--output-on-failure']"

      - name: Install
        run: |
          cmake --install ${{ github.workspace }}/build/ninja-vcpkg --component server --prefix ${{ github.workspace }}/install

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: snail-server-${{ matrix.arch }}-${{ matrix.platform }}
          path: ${{ github.workspace }}/install/bin/snail-server*
