name: clang-format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  job:
    name: Check clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './snail ./tests'
        exclude: './snail/common/third_party'
        extensions: 'cpp,hpp'
        clangFormatVersion: 16

    # - uses: EndBug/add-and-commit@v9
    #   with:
    #     author_name: Clang Robot
    #     author_email: robot@example.com
    #     message: 'Committing clang-format changes'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
