name: Update Test Data

on:
  workflow_dispatch:

jobs:
  job:
    name: update-${{ matrix.run-on }}

    runs-on: ${{ matrix.run-on }}

    strategy:
      fail-fast: false
      matrix:
        run-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install ninja
        if: runner.os == 'Linux'
        run: sudo apt install ninja-build

      - uses: TheMrMilchmann/setup-msvc-dev@v2
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Configure
        run: cmake -G Ninja ${{ github.workspace }}/tests/apps

      - name: Build
        run: ninja

      - name: Build & Install Apps
        run: ninja install-apps

      - name: Record
        run: ninja -j1 record

      - name: Install Records
        run: ninja install-records

      - name: Pack & Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-data-${{ matrix.run-on }}
          path: ${{ github.workspace }}/tests/apps/*/dist/**
